### PR TITLE
Added ExpectAny function.

### PR DESCRIPTION
**Pull request by KSmerda**
I needed the functionality for expecting any of multiple given strings and knowing which one was found. Usage scenario: remote sessions to various equipment while not knowing which individual piece of equipment will respond. Using this function it is possible to provide any possible expected string, and the function will return the first found string, thus identifying the device which responds.

### CODE REVIEW

**Comment by ThomasRooney** [comment]
Hi, I saw your pull request and thought that this usage scenario would be handled better by regex matching. So I spent a few hours today and implemented that. I've committed a change adding the `ExpectRegexFind(pattern)` function, which will return an array containing matched subexpressions. 

Does this solve your use case? I did this because I thought the scenario you described would be better handled by a slightly more generic function. I thought it would be a simpler way to do this than keeping track of several sliding windows in KMP as you seem to have implemented.

**Comment by KSmerda** [comment]
Seems I had an a bit older version of the file locally, the one where regex matching was not yet working properly, so I expanded the single string functionality.

Your solution does appear to be better. I'll try it out in the next few days and provide feedback.

**Comment by KSmerda** [comment]
Hi!
Your function works and covers my usage scenario, but during testing I noticed a potential problem. One of my the remote sessions generates only the following output:
">>User name:_"
Quotation marks not included in the output, underscore represents the location of the cursor (there is no space between the colon and the cursor).
The function would successfully find the following strings:
">>User"
">>User n"
">>User na"
but would fail to find:
">>User nam"
">>User name"
">>User name:"

It's not a big problem for me because I don't have a case where I would have to differentiate between two pieces of equipment based on the last few characters, but I thought I'd let you know.

Thank you for the effort you put into this, the library has been very useful so far!

**Comment by ThomasRooney** [comment]
(1 year on, apologies for the delay). ^^ This should have been fixed by recent changes. Closing the PR

**Pull request closed without merging**
